#!/usr/bin/env perl

system("make -f Makefile.in mairix.txt");
unlink "build_kit";

($version = $ARGV[0]) || ($version = "UNKNOWN");

open (IN, "<mairix.spec.sample");
open (OUT, ">mairix.spec");
while (<IN>) {
  s/\@\@VERSION\@\@/$version/;
  print OUT;
}
close (IN);
close (OUT);

unlink "mairix.spec.sample";

system("cvs export -d dfasyn -r V0_3 dfasyn");

